### ISSUE TITLE
Optimize build process

### ISSUE THREAD

**Issue by Zarthus** [Hacker0x01/docs.hackerone.com#1056]
From the build logs:

```
warning Your GraphQL query in createPages took 30.458 seconds which is an unexpectedly long time. See https://gatsby.dev/create-pages-performance for tips on how to improve this.
```

https://gatsby.dev/create-pages-performance 

Probably relatively low priority, but maybe there's some low hanging fruit fixes we can do here.

**Comment by martijnrusschen** [comment]
Here's my attempt from 2 years ago: https://github.com/Hacker0x01/docs.hackerone.com/pull/323. Never trusted this enough to roll out, but may be worth a try. The build time reduces with 80% using this.
