### ISSUE TITLE
### PullRequest Breakdown

### ISSUE THREAD

**Issue by Bientranbao** [Hacker0x01/docs.hackerone.com#1078]
### PullRequest Breakdown
**Reviewable lines of change**
```diff
+ 87
- 9

95% Markdown
5% YAML
<1% Other
```
**Type of change**
```
Feature - These changes are adding a new feature or improvement to existing code.
```
<table id="pr-rule-based-message">
    <thead>
        <tr>
            <th width="50"></th>
            <th width="100%">
                1 Message
            </th>
        </tr>
    </thead>
    <tbody>
                    <tr>
                <td>📚</td>
                <td>
                    It looks like the description for this pull request is either blank or very short. Adding a high-level summary will help our reviewers provide better feedback. Feel free to include questions for PullRequest reviewers and make specific feedback requests.
                                    </td>
            </tr>
                    </tbody>
</table>
<p align="right">
    <a href="https://app.pullrequest.com/dash/projects/1/Hacker0x01/docs.hackerone.com">
                    <img width="15%" src="https://static.pullrequest.com/images/dashboard/pullrequest-logo.svg">
            </a>
</p>

_Originally posted by @pullrequest[bot] in https://github.com/Hacker0x01/docs.hackerone.com/pull/1067#pullrequestreview-1519175557_

**Comment by Apetree100122** [comment]
https://github.com/Hacker0x01/docs.hackerone.com/issues/1078#issue-1804304073
