### ISSUE TITLE
Average bounty $ = mode? Median?

### ISSUE THREAD

**Issue by laurentopia** [Hacker0x01/docs.hackerone.com#1111]
Just checking.
I see many at super low average with low report count with high bounty total, can't be mean, could be median.

**Comment by Zarthus** [comment]
Hi,

I can confirm it's the median. I did a research into this a month ago as well -- my suggested fix at the time was to replace "Average" with "Median" at the time but it never picked up enough steam to get it over the finish line.

![Screenshot 2023-08-15 at 14 23 52](https://github.com/Hacker0x01/docs.hackerone.com/assets/3660408/db0cc02d-da3a-4ce8-a506-b78450e89f2f)

cc @jessiwright

**Comment by laurentopia** [comment]
> Hi,
> 
> I can confirm it's the median. I did a research into this a month ago as well -- my suggested fix at the time was to replace "Average" with "Median" at the time but it never picked up enough steam to get it over the finish line.
> 
> ![Screenshot 2023-08-15 at 14 23 52](https://user-images.githubusercontent.com/3660408/260708592-db0cc02d-da3a-4ce8-a506-b78450e89f2f.png)
> 
> cc @jessiwright

few know that there are many types of average but nobody knows what median means. I suggest calling it "media average" to cater to both crowds.
