### ISSUE TITLE
Typo on Human Augmented Signal auto reply

### ISSUE THREAD

**Issue by testerting** [Hacker0x01/docs.hackerone.com#114]
Not really in this doc repo. But cannot find a better place to report

![typo](https://user-images.githubusercontent.com/32080604/60700689-2179df00-9f3c-11e9-92f5-78402f120e58.jpg)

**Comment by stacyspiva** [comment]
thanks for catching this! We'll escalate it to the right folks to fix!

**Comment by 15388734337** [comment]
> 谢谢你抓住这个！我们会把它升级到合适的人来解决！

**Comment by 15388734337** [comment]
> 不是真的在这个doc repo。但找不到更好的报道地点
> 
> ![错字](https://user-images.githubusercontent.com/32080604/60700689-2179df00-9f3c-11e9-92f5-78402f120e58.jpg)

**Comment by martijnrusschen** [comment]
This should be fixed.
