### ISSUE TITLE
Problem with the perticular website page

### ISSUE THREAD

**Issue by vijay3778** [Hacker0x01/docs.hackerone.com#136]
even if i am LOGGED IN this page wants me to make a new account on HackerOne website,it could cause some security issues please loook forward to it. 

![Screenshot (191)](https://user-images.githubusercontent.com/43614312/65625721-01f9cc00-dfea-11e9-95a1-24a844ef4992.png)

**Comment by reedloden** [comment]
If you believe you've found a security issue, please report it to https://hackerone.com/security.

If you have found a functional bug, please report it to support@hackerone.com.

**Comment by vijay3778** [comment]
Can my previous mail be forwarded to support team

**Comment by reedloden** [comment]
Unfortunately, no. You'll need to submit it yourself.
