### ISSUE TITLE
docs.hackerone.com doesn't render properly on IE 11

### ISSUE THREAD

**Issue by mralekzandr** [Hacker0x01/docs.hackerone.com#139]
A customer first noticed this issue when he clicked on the `?`next to the Severity ratings on the embedded submission form (see screenshot). When he clicked that, the page loaded (albeit rendered wonkily). But as soon as he tried scrolling, the contents of the page seemed to disappear.

I just tried testing it on my own device, and clicking that `?`opens the page but renders nothing. Going directly to docs.hackerone.com also renders nothing.

![Screen Shot 2019-10-10 at 4 49 03 PM](https://user-images.githubusercontent.com/55005085/66609136-e4963780-eb7d-11e9-8542-d172a7ee2406.png)

**Comment by reedloden** [comment]
Do you get anything in the browser console when this happens?

Go to: Menu cog icon > F12 Developer Tools > Console tab
https://msdn.microsoft.com/en-us/library/bg182326(v=vs.85).aspx
