### ISSUE TITLE
Invalid edit this page link due to renaming

### ISSUE THREAD

**Issue by jmayntzhusen** [Hacker0x01/docs.hackerone.com#234]
Hi there!

Was browsing your documentation and found a broken link, when I found the updated one I wanted to submit a PR to update it, and discovered that the "edit this page" button also had a different broken link.

Can't contribute to that button as far as I can see..
![image](https://user-images.githubusercontent.com/36075913/91444495-1b983900-e875-11ea-8fc4-8d8521fef6d8.png)

Leads to:
`https://github.com/Hacker0x01/docs.hackerone.com/edit/master/docs/programs/good-program.md`
Should lead to:
`https://github.com/Hacker0x01/docs.hackerone.com/blob/master/docs/programs/run-a-good-program.md`

**Comment by reedloden** [comment]
Thanks. This is fixed in https://github.com/Hacker0x01/docs.hackerone.com/commit/04be399ae52a9108d0a1e818fb9a15bc7af71d28. :-)
