### ISSUE TITLE
If the e-mail used at sign-up does not exist at the time of registration, you can't re-send confirmation e-mail.

### ISSUE THREAD

**Issue by jtagcat** [Hacker0x01/docs.hackerone.com#285]
Don't really know where else to report this.

Yes, you can send confirmation e-mail again, when at the registration page, but a while later, you can't. Even after resetting password e-mail, you can't.

**Comment by stacyspiva** [comment]
hi @jtagcat, if you're running into problems with the product, you can report issues here at: support@hackerone.com. 

Thanks!
