### ISSUE TITLE
Add docs on how to change severity

### ISSUE THREAD

**Issue by wbt** [Hacker0x01/docs.hackerone.com#508]
Is it possible to change the CVSS / Severity ratings after discussion/new information comes to light, to make that signal more accurate using the latest & best information available?

If so, it would be nice to document how at: https://docs.hackerone.com/hackers/severity.html

**Comment by chriszo111** [comment]
@wbt it is possible to change the severity after a report has been submitted. You can do this by clicking the "pen" icon next to the severity in the report metadata sidebar: 

<img width="311" alt="image" src="https://user-images.githubusercontent.com/7249742/187688977-5094adc2-e031-48fa-a7f9-2b273bbbdbe4.png">

We've noted down your request to add it to the docs. Thank you for your input!
