### ISSUE TITLE
Brinqa integration page missing?

### ISSUE THREAD

**Issue by whisk3ykilo** [Hacker0x01/docs.hackerone.com#526]
Does HackerOne still integrate with Brinqa? If so, having the integration steps available on the docs site would be helpful.

[https://www.brinqa.com/resource/brinqa-hackerone-jsb](https://www.brinqa.com/resource/brinqa-hackerone-jsb)

**Comment by whisk3ykilo** [comment]
Also not listed on /integrations in the product itself (at least, in the demo env)

**Comment by jessiwright** [comment]
I sent you both an invite to the google doc draft of this. Let me know what you think.

**Comment by martijnrusschen** [comment]
It's live now: https://docs.hackerone.com/programs/brinqa-integration.html
