### ISSUE TITLE
Too many redirects to link to blog post

### ISSUE THREAD

**Issue by bwjohnson-ss** [Hacker0x01/docs.hackerone.com#617]
https://github.com/Hacker0x01/docs.hackerone.com/blob/f8e13c31ae373705fd6c8debf7089acb33723022/docs/programs/severity.md?plain=1#L38

https://www.hackerone.com/blog/introducing-severity-cvss

https://www.hackerone.com/vulnerability-management/critical-introducing-severity-cvss

Results in ERR_TOO_MANY_REDIRECTS

**Comment by Chukotown915** [comment]
> here

Iam getting kacked by a LGK32 my phone its an LG L322

**Comment by jessiwright** [comment]
@bwjohnson-ss Thanks for bringing this up! I found the replacement link and will be pushing an update through today.
