### ISSUE TITLE
@wbt it is possible to change the severity after a report has been submitted. You can do this by clicking the "pen" icon next to the severity in the report metadata sidebar:

### ISSUE THREAD

**Issue by kirmo9** [Hacker0x01/docs.hackerone.com#766]
@wbt it is possible to change the severity after a report has been submitted. You can do this by clicking the "pen" icon next to the severity in the report metadata sidebar: 

<img width="311" alt="image" src="https://user-images.githubusercontent.com/7249742/187688977-5094adc2-e031-48fa-a7f9-2b273bbbdbe4.png">

We've noted down your request to add it to the docs. Thank you for your input!

_Originally posted by @chriszo111 in https://github.com/Hacker0x01/docs.hackerone.com/issues/508#issuecomment-1232937538_

**Comment by wbt** [comment]
Looks like a spam autorepost to generate activity in the graph
