### ISSUE TITLE
Typo on Jira Cloud Doc

### ISSUE THREAD

**Issue by antoineh1** [Hacker0x01/docs.hackerone.com#79]
On Step 3, the document tells you to pick "Jira Server", but I think it is supposed to say "Jira Cloud".

**Comment by stacyspiva** [comment]
Thanks again @antoineh1 for catching this mistake! It is indeed supposed to say Jira Cloud. Let us know if you find any more issues!

**Comment by 15388734337** [comment]
输入法错误

**Comment by 15388734337** [comment]
> 在第3步，文档告诉您选择“Jira Server”，但我认为应该说“Jira Cloud”。

**Comment by 15388734337** [comment]
> 再次感谢@ antoineh1抓住这个错误！确实应该说Jira Cloud。如果您发现更多问题，请告诉我们！

**Comment by 15388734337** [comment]
> 再次感谢@ antoineh1抓住这个错误！确实应该说Jira Cloud。如果您发现更多问题，请告诉我们！
