### ISSUE TITLE
Dead link at /hackers/publishing-external-vulnerabilities.html

### ISSUE THREAD

**Issue by Spam404** [Hacker0x01/docs.hackerone.com#84]
A dead link exists [here](https://docs.hackerone.com/hackers/publishing-external-vulnerabilities.html). It's available on GitHub [here](https://github.com/Hacker0x01/docs.hackerone.com/blob/master/docs/hackers/publishing-external-vulnerabilities.md).

It's the last link, "Reputation". The URL mistakenly includes a `>` making the final URL `/>hackers/reputation.html` which doesn't exist.

**Comment by reedloden** [comment]
Thanks, @Spam404!
