### ISSUE TITLE
/hackers/publishing-external-vulnerabilities.md missing link

### ISSUE THREAD

**Issue by eligrey** [Hacker0x01/docs.hackerone.com#91]
There is no link on /hackers/publishing-external-vulnerabilities.md to see the vulnerabilities you've submitted that are pending review. I can't find such a link on the entire HackerOne site.

This probably results in users submitting external vulnerability reports multiple times as they cannot see their own previous submissions without storing the resulting URL.

**Comment by stacyspiva** [comment]
@eligrey thanks for bringing this issue up! We currently don't surface published reports in a user's Inbox to prevent an information leak. We've forwarded your request to the appropriate product manager and engineering team to see how they can prioritize and fix the issue.

**Comment by clinboy247** [comment]
how can i start on this site

**Comment by 15388734337** [comment]
> /hackers/publishing-external-vulnerabilities.md上没有链接可以查看您提交的待审核漏洞。我在整个HackerOne网站上找不到这样的链接。
> 
> 这可能导致用户多次提交外部漏洞报告，因为他们无法查看自己以前提交的内容而不存储生成的URL。

**Comment by 15388734337** [comment]
> @eligrey感谢您提出这个问题！我们目前不会在用户的收件箱中显示已发布的报告，以防止信息泄露。我们已将您的请求转发给相应的产品经理和工程团队，以了解他们如何确定问题的优先顺序并解决问题。

**Comment by 15388734337** [comment]
> 我怎么能在这个网站上开始

**Comment by sutee2530** [comment]
> There is no link on /hackers/publishing-external-vulnerabilities.md to see the vulnerabilities you've submitted that are pending review. I can't find such a link on the entire HackerOne site.
> 
> This probably results in users submitting external vulnerability reports multiple times as they cannot see their own previous submissions without storing the resulting URL.

**Comment by shahidul3773** [comment]
![123795077_413010819702540_1685425244698059547_n](https://user-images.githubusercontent.com/47246960/103787688-18555b00-5068-11eb-9b8b-add32eaf5052.jpg)

**Comment by Sridhar-rajendran** [comment]
Hi 🙂
